### ISSUE TITLE
Channel Questions

### ISSUE THREAD

**Issue by MidoThePanda** [Murgeye/teamspeak3-python-api#12]
Hey there,
I've tried our your API and it is working nicely, but I have one question.
Is there a way to edit a TeamSpeak channel using your API?

Thx
Green_Panda

**Comment by Murgeye** [comment]
Hey,

the channeledit command is currently not explicitly implemented, but generally you can call it - like any API command - by calling
`ts3conn.channeledit(cid=channelID, channel_description="New Description")`

You can see all modifiable parameters in the channel properties section in [the Server Query Manual](https://www.teamspeak-info.de/downloads/ts3_serverquery_manual.pdf). Beware, the manual is notoriously bad at replacing spaces with underscores (e.g. `channel codec` should really be `channel_codec`).

Regards
Fabian

**Comment by Murgeye** [comment]
Hi,
Any news on this? Did this work for you?

Regards
Fabian

**Comment by MidoThePanda** [comment]
Sry I saw your answer just a moment ago, I switched to java in order to link some other stuff for my bot (and also Linux doesn't really like Python and I was trying to run it on a Linux Server) so I didn't try It out, but thx for the help anyways. If I ever code a TS3Bot with Python again, I will sure try it. :D

**Comment by Murgeye** [comment]
Alright, I am going to close this issue.
Just curious, what do you mean by "Linux doesn't really like Python?". I am running a Bot based on this API on a Linux server as well and never had any problems with Python.
