### ISSUE TITLE
Change Server Group

### ISSUE THREAD

**Issue by JakobRinke** [Murgeye/teamspeak3-python-api#14]
How to Change the Server Group of a Client?

**Comment by Murgeye** [comment]
You should be able to do that using 
```
servergroupaddclient(sgid=servergroup_id, cldbid=client_db_id)  
```

In general, you can simply call any function from the server query manual using keyword arguments, even if it's not explicitly implemented in code in the API.

You can check the manual, for example, here [https://lethallhost.com.br/clientes/TeamSpeak%203%20Server%20Query%20Manual.pdf](https://lethallhost.com.br/clientes/TeamSpeak%203%20Server%20Query%20Manual.pdf)

Or it should come with your server installation.

**Comment by JakobRinke** [comment]
Thank You
