### ISSUE TITLE
Channel event

### ISSUE THREAD

**Issue by Jan3kk** [Murgeye/teamspeak3-python-api#15]
Hello :)
I created a function that is called everytime a client moves himself into a channel with channel_id of x.
And in that function, let's call it foo_event(), I need to have ID of the channel that I connected with foo_event.
Can it be done somehow or maybe you can edit Event.py and pass it through blinker module?

Example what I want to achieve:

main.js:

ts3conn.register_for_channel_events(x, foo_event)

module_1.js:

def foo_event(sender, **):
----if isinstance(event, Events.ClientMovedSelf):
--------if event.target_channel_id == event.id_of_registered_event:  # <-- example name of new variable
------------pass
------------# the rest of the code

**Comment by Murgeye** [comment]
Hi,

Have you found a solution for this? Otherwise I usually do stuff like this with a decorator which essentially creates a new function for each channel.
