### ISSUE TITLE
Request for clientpoke support

### ISSUE THREAD

**Issue by Zedjones** [Murgeye/teamspeak3-python-api#18]
I'd like to add the ability to poke users from a Matrix bot, but there doesn't seem to be any way to do so with this library currently (unless I'm missing something).

I can probably get around this by using the private `_send` function, but proper support would be great.

Thanks for the awesome work on this! It's definitely an improvement over the library I was using before.

**Comment by Murgeye** [comment]
I have just added explicit support for this (will also be updated on pip in a few minutes).

However, you could have called clientpoke without an explicit implementation by looking up the parameters in the server query manual. TS3Connection.<command>(kwargs) will call the <command>, even if it is not explicitly implemented by sending the command + any keyword arguments. So you could have called

`ts3conn.clientpoke(clid=client["clid"], msg=message)`

The explict implementation I just added simply allows you to leave out the parameter names:

`ts3conn.clientpoke(client["clid"], message)`

> Thanks for the awesome work on this! It's definitely an improvement over the library I was using before.

Thanks for the praise, and feel free to open another issue if you are missing something/have any problems.

**Comment by Zedjones** [comment]
Awesome, I didn't realize you could do that for any of the commands, that's good to know! Thanks for the quick response implementation :)
