### ISSUE TITLE
Request for client ban

### ISSUE THREAD

**Issue by vessosa** [Murgeye/teamspeak3-python-api#19]
Hi,
It's possible to add a client ban command? Thank you!

**Comment by Murgeye** [comment]
As with any command that is not explicitly implemented by the API, you can get the parameters from the Server Query Manual and simply call the command using keyword arguments. In this case, the manual states:

```
banclient clid={clientID} [time={timeInSeconds}] [banreason={text}]
```

So you can call

```
ts3conn.banclient(clid={clientID}, time={timeInSeconds}, banreason={text})
```

You can also leave out the time and banreason.

This is without testing right now, but should work. If it doesn't, I can take a look tomorrow.

**Comment by vessosa** [comment]
cool, thank you! do you know which one is the equivalent for banning a IP range?

**Comment by Murgeye** [comment]
Should be banadd:

 
```
BANADD

Adds a new ban rule on the selected virtual server. All parameters are optional but at least one of the following 
must be set: ip, name, or uid.

Permissions:
b_client_ban_create

Syntax:
banadd [ip={regexp}] [name={regexp}] [uid={clientUID}]
[time={timeInSeconds}] [banreason={text}]

Example:
banadd ip=1.2.3.4 banreason=just\s4\sfun
banid=1

error id=0 msg=ok
```

**Comment by vessosa** [comment]
thank you very much!
