### ISSUE TITLE
Register for log events

### ISSUE THREAD

**Issue by vessosa** [Murgeye/teamspeak3-python-api#20]
I'm trying to find a way to know who was the user that gives permission to another user. Something like an internal tag or field for each user pointing to who has done that. While I don't believe that TS does that by default, I'm thinking to use the log events:
ts3conn.logview()
To retrieve the latest logs, so I have to parse and analyze who gives permissions to who, to finally store in a database.
My question is: there is a way to write a "register_for_logs_events" following the standards that you already did for "server_events, private_messages_channel_events"? It will be a lot easy to receive events of the logs instead of reading everything.

**Comment by vessosa** [comment]
Or maybe something like register_for_permissions_change..
I could use custominfo to store that info.

**Comment by Murgeye** [comment]
I'm not really sure what you are trying to do. Registering to server/channel/text events is done using the TS3 query call
`servernotifyregister event={server|channel|textserver|textchannel|textprivate} [id={channelID}]`

which already gives you the events when they happen. However, there seems to be no way to get notified for log events by the server. If you want to get all of these events you would indeed have to call `logview` using a comparator and check if you got all of them.
