### ISSUE TITLE
Introduce Github Releases

### ISSUE THREAD

**Issue by Sebbo94BY** [Murgeye/teamspeak3-python-api#24]
Hey,
What do you think about publishing Github releases, when a new version is available?

This would allow the get new changes on the `master`/`main` branch at any time and people who are using this project, could simply decide to use a specific version (release) of this project. (Instead of using a Git commit reference.)

The release could also automatically generate a changelog with references to e.g. issues and pull requests. :)

Doing this manually, are three clicks or so. But I'm sure, that we could also automate this using a Github workflow.

**Comment by Murgeye** [comment]
Hey,
I think this is a good idea. However, I would keep it somewhat manual and connect it with pushing a new release to pypi. Thank you for the idea, I hope I will get to it this week 👍

**Comment by Sebbo94BY** [comment]
You're welcome. Thanks for the first release! :)
