### ISSUE TITLE
Add API to pip repositories

### ISSUE THREAD

**Issue by nisutec** [Murgeye/teamspeak3-python-api#7]
Hallo,
I can't find your project under the pip repository https://pypi.python.org/simple.
How i can import your api in my project ?

**Comment by Murgeye** [comment]
Hey,
I have not gone through the process of adding the API to pip (I should probably look into how to do that). For now I recommend cloning (or adding it as a git submodule if your project is a git project) and importing the API locally. E.g. when the API is located in the ts3API folder inside your project you can import it like this (see the code example in the README or my [ts3Bot project](https://github.com/Murgeye/teamspeak3-python-bot)):

```
from ts3API.TS3Connection import TS3Connection
import ts3API.Events as Events
```

But I will try to find out how to add the API to pip!

**Comment by Rindula** [comment]
I'm also interested in this as a pip package. Here is a neat guide on how to set it up: https://dzone.com/articles/executable-package-pip-install

**Comment by Murgeye** [comment]
@Rindula Thanks for mentioning this issue again, I kinda forgot that I never got around to doing this. I will try to find some time (hopefully this week/next weekend) to finally do that.

**Comment by Murgeye** [comment]
I finally got around to doing this: [https://pypi.org/project/ts3API/](https://pypi.org/project/ts3API/) 

Now you can install this package using
```
pip install ts3API
```

I appreciate any feedback on the package!
