### ISSUE TITLE
New Events for Servergroups & Channelgroups

### ISSUE THREAD

**Issue by nisutec** [Murgeye/teamspeak3-python-api#9]
Please add a event for Servergroup changes and Channelgroup changes like as adding or removing a user from a group.

**Comment by Murgeye** [comment]
The server does not supply events for that, see e.g.:
https://forum.teamspeak.com/threads/82290-Notify-on-group-change

Therefore there is nothing I can do to add these to the API.

I think you will have to query for these changes via `clientinfo` in a loop .

**Comment by nisutec** [comment]
Ok that is sad that there is no event for it.
